workflows:
  ios-build:
    name: Bikram iOS Build
    environment:
      xcode: latest
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: master
          include: true
    scripts:
      - name: List Xcode Schemes
        script: |
          echo "Listing available schemes in your project..."
          xcodebuild -list -project BikramCalendarApp.xcodeproj
      - name: Build the app
        script: |
          xcodebuild -project BikramCalendarApp.xcodeproj \
                     -scheme BikramCalendarApp \
                     -sdk iphoneos \
                     -configuration Release \
                     CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
    artifacts:
      - build/ios/iphoneos/*.app
